SET EMTEXDIR=C:\EMTEX
SET DVIDRVINPUT=C:\EMTEX\DOC
SET DVIDRVFONTS=C:\TEXFONTS
SET MFJOBOPT=/3/Z
del sd_doc.toc
del sd_doc.aux
tex386 sessions.txi
tex386 demo.txi
tex386 relnotes.txi
tex386 sd_doc.txi
tex386 sd_doc.txi
