srcdir = .

RM = del
MAKEINFO = makeinfo --no-split
MAKE_ASCII = makeinfo --no-split --no-headers
TXI2DVI = tex
TXI2PDF = pdftex
DVIPS = dvips
CRFIX = crfix
TXI2HTML = makeinfo --html

.SUFFIXES: .dvi .info .txt .txi .pdf .html

all: sessions.all sd_doc.all demo.all relnotes.all relnotes98.all relnotes03.all relnotes09.all sample.html install

.txi.pdf:
	$(TXI2PDF) $<
	$(TXI2PDF) $<


plain::
	./makeinfo --no-split --no-headers -o demo.txt demo.txi \
#	\bin\fixthisfile.cmd     demo.txt


pdf.all: demo.pdf sessions.pdf sd_doc.pdf relnotes.pdf relnotes98.pdf relnotes03.pdf relnotes09.pdf \
         appnote1.pdf appnote2.pdf appnote3.pdf appnote4.pdf




clean::
	rm sd_doc.txt sd_doc.pdf sd_doc.html sd_doc_*.html \
           demo.txt demo.pdf demo.html \
           appnote*.txt appnote*.pdf appnote*.html \
           sessions.txt sessions.pdf sessions.html sessions_toc.html \
           relnotes.txt relnotes.pdf relnotes.html \
           relnotes98.txt relnotes98.pdf relnotes98.html \
           relnotes03.txt relnotes03.pdf relnotes03.html \
           relnotes09.txt relnotes09.pdf relnotes09.html \
           faq.html sample.html \
           *.ps *.pdf \
           psdoc.exe textdoc.exe pdfdoc.exe \
           install.exe installw.exe installs.exe \
           *.asc *.gz *.dvi






cleanup::
	rm *.o libsdlib.a

savesource::
	rm ..\sddoc\sd_source.zip
	zip ..\sddoc\sd_source $(SDLIB_OBJS:.o=.cpp) $(SDTTY_OBJS:.o=.cpp) \
               $(SD_OBJS:.o=.cpp) $(MKCALLS_OBJS:.o=.cpp) $(HFILES) \
               sd.rc sdtty.rc sdui-ttu.cpp $(ICONS) $(SHORTCUTS) \
               sd.bmp $(MAKEFILES) sd_calls.txt db_doc.txt COPYING.txt
